### ISSUE TITLE
@4.0: UnhandledPromiseRejectionWarning: Error: Unexpected HTTP response: 403

### ISSUE THREAD

**Issue by avelino** [DeLaGuardo/setup-clojure#42]
```
Run DeLaGuardo/setup-clojure@4.0
[2](https://github.com/avelino/moclojer/runs/5322276602?check_suite_focus=true#step:4:2)
  with:
[3](https://github.com/avelino/moclojer/runs/5322276602?check_suite_focus=true#step:4:3)
    cli: 1.10.2
[4](https://github.com/avelino/moclojer/runs/5322276602?check_suite_focus=true#step:4:4)
    github-token: ***
[5](https://github.com/avelino/moclojer/runs/5322276602?check_suite_focus=true#step:4:5)
  env:
[6](https://github.com/avelino/moclojer/runs/5322276602?check_suite_focus=true#step:4:6)
    JAVA_HOME: /opt/hostedtoolcache/GraalVM/21.0.0-java11-amd64/x64
[7](https://github.com/avelino/moclojer/runs/5322276602?check_suite_focus=true#step:4:7)
    JAVA_HOME_21.0.0.java11.amd64: /opt/hostedtoolcache/GraalVM/21.0.0-java11-amd64/x64
[8](https://github.com/avelino/moclojer/runs/5322276602?check_suite_focus=true#step:4:8)
    GRAALVM_HOME: /opt/hostedtoolcache/GraalVM/21.0.0-java11-amd64/x64
[9](https://github.com/avelino/moclojer/runs/5322276602?check_suite_focus=true#step:4:9)
(node:1651) UnhandledPromiseRejectionWarning: Error: Unexpected HTTP response: 403
[10](https://github.com/avelino/moclojer/runs/5322276602?check_suite_focus=true#step:4:10)
    at /home/runner/work/_actions/DeLaGuardo/setup-clojure/4.0/node_modules/@actions/tool-cache/lib/tool-cache.js:[11](https://github.com/avelino/moclojer/runs/5322276602?check_suite_focus=true#step:4:11)4:1
11
    at Generator.next (<anonymous>)
[12](https://github.com/avelino/moclojer/runs/5322276602?check_suite_focus=true#step:4:12)
    at fulfilled (/home/runner/work/_actions/DeLaGuardo/setup-clojure/4.0/node_modules/@actions/tool-cache/lib/tool-cache.js:24:42)
[13](https://github.com/avelino/moclojer/runs/5322276602?check_suite_focus=true#step:4:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[14](https://github.com/avelino/moclojer/runs/5322276602?check_suite_focus=true#step:4:14)
(node:1651) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[15](https://github.com/avelino/moclojer/runs/5322276602?check_suite_focus=true#step:4:15)
(node:1651) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

https://github.com/avelino/moclojer/runs/5322276602?check_suite_focus=true

**Comment by DeLaGuardo** [comment]
Thanks for your support!

That is a nasty exception :( The root cause is actually "unknown clojure cli version" but without proper error handling, it did not produce an error. Totally my fault, I will change the error handler to give a meaningful message and early termination of the action. Could you try another version from [this](https://clojure.org/releases/tools) list?
